language: ruby
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild 

script: ./script/cibuild

after_success: gulp 

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master