#Configuración
title: Prácticas ULL
email: alu0101283197@ull.edu.es
description: >- # this means to ignore newlines until "baseurl:"
  Resumen de las prácticas de Systemas y Técnologias Web: Servidor - Universidad de La Laguna
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jekyll.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Felipe5Valencia
incremental: true

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

collections:
  - character

